### ISSUE TITLE
Cannot display properties of some iterable resources

### ISSUE THREAD

**Issue by matthieu-fesselier** [solid/query-ldflex#33]
When I iterate on the resources of a container, I cannot get its properties. For example: 
```javascript
for await (let res of solid.data["https://api.test-paris.happy-dev.fr/sources/users/"].ldp_contains) {
  console.log(`${await res.type}`)
}
// shows "http://www.w3.org/ns/ldp#Container" twice, I expected "sib:source" twice
```

It appears that `res.type` is actually an `AsyncIterator` which returns all the types in a document:
```javascript
for await (let res of solid.data["https://api.test-paris.happy-dev.fr/sources/users/"].ldp_contains) {
  for await (const type of res.type) {
    console.log(`${type}`);
  }
}
/* Result:
http://www.w3.org/ns/ldp#Container
3  http://www.w3.org/ns/auth/acl#Read
2  sib:source
http://www.w3.org/ns/ldp#Container
3  http://www.w3.org/ns/auth/acl#Read
2  sib:source
*/
```

Is the fact that there is no `@id` on these resources the source of the issue?

**Comment by RubenVerborgh** [comment]
> Is the fact that there is no @id on these resources the source of the issue?

Yes. It is caused by blank nodes, which only have meaning within one scope.
Simply said: you cannot look up more information about a blank node, because it's identifier is meaningless by the time you want to reuse it.

The problem is that `solid.data["https://api.test-paris.happy-dev.fr/sources/users/"].ldp_contains` [results in two blank nodes](https://solid.github.io/ldflex-playground/#%5B%22https%3A%2F%2Fapi.test-paris.happy-dev.fr%2Fsources%2Fusers%2F%22%5D.ldp_contains).

So when you do an `let … of` on this expression, it will yield two blank nodes (wrapped in an LDflex path).

So then you then do `.type` on those blank nodes. If you do `res.type.sparql`, you will see that this actually corresponds to `SELECT ?o { _:b3 rdf:type ?o }`. In other words: give me any type. Which is the result you get: it's the first type it finds.

Note that the expression `https://solid.github.io/ldflex-playground/#%5B%22https%3A%2F%2Fapi.test-paris.happy-dev.fr%2Fsources%2Fusers%2F%22%5D.ldp_contains.type` [gives you the right answer], because no blank node remain in scope.

> It appears that `res.type` is actually an `AsyncIterator`

It is many things actually 🙂
It is an LDflex path, `BlankNode`, thenable, and `AsyncIterable`—all at the same time.

> which returns all the types in a document:

Correct, as per the above blank node interpretation.

---

At the moment, this is defined/intended behavior. But I can see that another behavior would be more convenient, so will create an issue for that.

**Comment by RubenVerborgh** [comment]
However, it's currently probably better to return _no_ results than to return _unexpected_ results.

**Comment by matthieu-fesselier** [comment]
Ok thanks for the reply! I'll follow what's going on in #34
