### ISSUE TITLE
Enable to use websockets

### ISSUE THREAD

**Issue by jairo-campos-JD** [solid/query-ldflex#6]

**Comment by james-martin-jd** [comment]
This is tracked in https://github.com/RubenVerborgh/LDflex-Comunica/issues/4, I'm not sure if there is any work to do in this repo for this feature.

**Comment by james-martin-jd** [comment]
Added a milestone, which is targeting a mid-March release

**Comment by RubenVerborgh** [comment]
@jairo-campos-JD @james-martin-jd Not entirely what you had in mind, but `solid.data.clearCache()` now clears the local cache as of v2.4.0.

Since LDflex is currently not using any websockets, it did not make much sense to use it just for cache invalidation. Rather, I assume that your application is already using websocjets, so whenever you see an update pass by, calling `solid.data.clearCache(document)` (the parameter being optional), you can get the desired result.
